### ISSUE TITLE
General comments are removed

### ISSUE THREAD

**Issue by joerocklin** [Qarik-Group/gitlab-codeowners-linter#29]
Hi there - I love the idea of this tool as part of the pre-commit workflow. However, when I tried to apply it to a project I have, it removed a general comment block I had at the top of my file. This was not expected.

Original File:

```
## This file determines who is marked on merge requests for approvals
## ...
## until the comment block is done

[Default Owners]
## Comments about this section
* @user1 @user2

[Group-A]
path1/ @groupa
path2/ @groupa

[Group-B]
path3/ @groupb
```

'Fixed' file:

```

[Default Owners]
## Comments about this section
* @user1 @user2

[Group-A]
path1/ @groupa
path2/ @groupa

[Group-B]
path3/ @groupb
```

**Comment by gasparev** [comment]
Hi! I can't reproduce your error with https://github.com/Qarik-Group/gitlab-codeowners-linter/pull/30, do you want to share your actual file so I can check it?

**Comment by gasparev** [comment]
Hey @joerocklin did you solve the issue?
